version: "2"
services:
  lgtmoon-app:
    image: lgtmoon:latest
    container_name: lgtmoon-app
    volumes:
      - .:/opt/lgtmoon
    ports:
      - 9000:9000
    command:
      - "bash"
      - "-c"
      - "sbt run"
  lgtmoon-postgresql:
    image: postgres:10.5
    container_name: lgtmoon-postgresql
    ports:
      - 5432:5432
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lgtmoon
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: postgres
